site_name: C++ Code Wiki
markdown_extensions:
    - pymdownx.snippets
nav:
    - Home: index.md
    - 'Basics':
        - Input & Output: io.md
    - 'X Window System':
        - Overview: xwindow/x11.md
        - Send Event: xwindow/xsendevent.md
        - Next Event: xwindow/xnextevent.md
theme: readthedocs
